### ISSUE TITLE
Support detection of an existing .babelrc file

### ISSUE THREAD

**Issue by AriaFallah** [steelbrain/ucompiler-plugin-babel#8]

**Comment by AriaFallah** [comment]
Actually nevermind 😛 

The reason I cared about this was because I actually have started to prefer gulp to ucompiler. The problem was that your `publish-helpers` have only support for ucompiler.

I've decided to instead fork your publish helpers here so I instead make it support the `npm run build` script in `package.json`. This way I can be using gulp, webpack, pundle, or whatever, but `npm run build` will always support all the different configurations.

https://github.com/AriaFallah/npm-publish

**Comment by steelbrain** [comment]
For the record, it does support stuff in `.babelrc` 😄
